spring.datasource.url=jdbc:mysql://gms-db.cvaqgsw6sobh.eu-north-1.rds.amazonaws.com:3306/gms_db
spring.datasource.username=admin
spring.datasource.password=Manthatech2025

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=0
spring.jpa.open-in-view=false

server.port=8080